In [2]:
import numpy as np
import pandas as pd

In [6]:
dist = {
    "name" : ['Aditya','Rohan','Sachin','Sankalp'],
     "age" : [20,23,24,25],
    "CGPA" : [9.22,7.9,8.99,9.31]
}

In [7]:
df = pd.DataFrame(dist)

In [8]:
df

      name  age  CGPA
0   Aditya   20  9.22
1    Rohan   23  7.90
2   Sachin   24  8.99
3  Sankalp   25  9.31

In [9]:
df.to_csv('Data.csv')

In [12]:
df.to_csv('Data_Without_Index.csv', index = False)

In [13]:
df.head(2)

     name  age  CGPA
0  Aditya   20  9.22
1   Rohan   23  7.90

In [14]:
df.tail(2)

      name  age  CGPA
2   Sachin   24  8.99
3  Sankalp   25  9.31

In [15]:
df.describe( )

             age      CGPA
count   4.000000  4.000000
mean   23.000000  8.855000
std     2.160247  0.650769
min    20.000000  7.900000
25%    22.250000  8.717500
50%    23.500000  9.105000
75%    24.250000  9.242500
max    25.000000  9.310000

In [25]:
New_Data = pd.read_csv('New_Data.csv')

In [26]:
New_Data

   Train No. Name Location
0        123    A        X
1        124    B        Y
2        125    C        Z
3        127    D        W

In [27]:
New_Data['Name']

0    A
1    B
2    C
3    D
Name: Name, dtype: str

In [28]:
New_Data['Name'][0]

'A'

In [32]:
New_Data['Name'][0] = 'B'

C:\Users\ASUS\AppData\Local\Temp\ipykernel_20464\3600245388.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  New_Data['Name'][0] = 'B'

In [31]:
New_Data['Name'][0]

'A'

In [34]:
New_Data.index = ['f','s','t','f']

In [35]:
New_Data

   Train No. Name Location
f        123    A        X
s        124    B        Y
t        125    C        Z
f        127    D        W

In [15]:
import pandas as pd 
newdf = pd.DataFrame({
    "Name" : ['Aditya' , 'Sachin',2]})

In [16]:
newdf.index

RangeIndex(start=0, stop=3, step=1)

In [18]:
newdf.columns

Index(['Name'], dtype='str')

In [19]:
newdf.dtypes

Name    object
dtype: object